version: "3.6"

services:
  redis:
    image: redis/redis-stack-server:7.2.0-v6
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    command: ["./wait-for-it.sh", "redis:6379", "--", "npm", "run", "build"]

volumes:
  redis_data:


